**1. 向量到底是什么？**
- 不要当成死板的数字表格，要想象成坐标系里有长度和方向的**箭头**。
- 空间里的每一个点，都可以看作是从原点射出的一个箭头。

**2. 基向量与线性组合：空间的“基本粒子”**
- $\hat{i}$ 和 $\hat{j}$ 就是网格的横纵基本单位（比如向右 1 步，向上 1 步）。
- 空间里任何一个向量，不过是把这两个基本单位**拉伸缩短**然后再**相加**组合出来的结果。

**3. 矩阵就是“动词”**
- 矩阵不是一堆数字，而是一种**对空间的变换（拉扯、挤压、旋转）**。
- 当一个矩阵乘一个向量，脑海里的画面应该是：**把这个向量扔进一个正在扭曲的空间里，看看它最后落在哪**。
- 矩阵里的列向量，记录的就是变换后，原来的 $\hat{i}$ 和 $\hat{j}$ 跑到了什么新位置。

**4. 矩阵乘法 = 连续的动作**
- 两个矩阵相乘（比如 $AB$），不是枯燥的算术题，而是**连续做两次空间变换**。
- 顺序是从右往左读：先做 $B$ 变换，再接着做 $A$ 变换（就像穿衣服，先穿内衣 $B$，再穿外套 $A$）。

# Day 2: 李宏毅机器学习核心概念

**核心思想**：机器学习本质上就是 **“让机器自己去寻找一个最合适的函数”**。

### 找函数三步曲 (以预测频道播放量为例)

**Step 1: 定义模型 (Model)**
- 机器不知道函数长什么样，需要我们先“猜”一个大致框架。
- 最简单的线性模型：$y = wx + b$
- $x$ 是已知的特征 (比如昨天的播放量)，$w$ 是权重 (Weight)，$b$ 是偏置 (Bias)，这两个是机器需要找的未知参数。

**Step 2: 定义损失函数 (Loss)**
- 设定一个“烂度”指标，用来评估当前这组 $w$ 和 $b$ 算出来的结果，距离真实数据有多大的偏差。
- Loss 越大，说明模型越烂；目标就是想尽办法让 Loss 越小越好。

**Step 3: 优化参数 (Optimization)**
- **核心武器**：梯度下降 (Gradient Descent)。
- **大白话理解**：就像蒙着眼睛找下山的路。计算一下当前位置脚底下的坡度（求导/算梯度），哪边往下指，就往哪边迈一步（更新参数）。
- 一步步迭代，直到走到谷底（Loss 最小的地方），此时手里的参数就是最佳参数。

---

### 从机器学习到深度学习

- **线性模型的局限 (Model Bias)**：直线就是直线，再怎么调也拟合不出复杂的规律曲线。
- **破局之法**：把许多个简单的非线性函数（比如 Sigmoid 或 ReLU）像拼乐高一样组合起来，就能逼近世界上任何复杂的折线/曲线。
- 当这些函数一层一层叠得非常深、参数量非常庞大时，这个模型就叫做**神经网络 (Neural Network)**，也就是我们说的**深度学习 (Deep Learning)**。

In [8]:
# pytorch 导入的是 torch
import torch

# 用 arange 创建一个行向量 x 包含以0开始的前12个整数
x = torch.arange(12)
print(x)

# 可以通过张量的 shape 属性来访问张量的形状
print(x.shape)

# 元素个数
print(x.numel())

# 改变已有张量的形状
X = x.reshape(3, 4)
print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
import torch

# 设置一些全0的张量
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
import torch

# 设置一些全1的张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
# 创建一定形状的随机正态分布张量
import torch
torch.randn(3, 4)

tensor([[ 0.3787, -0.9533, -2.5494, -0.1862],
        [-0.2029, -0.1927, -0.0570, -1.2361],
        [ 0.5130, -0.7348, -0.3027,  0.0655]])

In [12]:
# 嵌套列表
import torch
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [1]:
# 一些基本的运算
import torch
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# 求幂 e 的次方
x = torch.tensor([1.0, 2, 4, 8])
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [3]:
# 将张量连结在一起形成大的张量
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2 ,3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [4]:
# 逻辑运算
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2 ,3, 4], [4, 3, 2, 1]])
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [5]:
# 张量中全部元素求和
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X.sum()

tensor(66.)

In [6]:
# 广播机制
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [ ]:
# 索引与切片
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [8]:
# 通过指定索引将元素写入矩阵
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
# 批量为多个元素赋值相同的值
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [11]:

# 原地分配: X += Y 或者 Z[:] = X + Y（ Y = X + Y 不是）
before = id(Y)
Y = Y + X
id(Y) == before
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 5121971424
id(Z): 5121971424


In [ ]:
# 转换为其他 Python 对象
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [13]:
# 将大小为1的张量转化为 Python 标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [14]:
# 自动微分的一个简单的例子
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [15]:
x.requires_grad_(True) # 等价于 x = torch.arange(4.0, requires_grad=True)
x.grad # 默认是 None

y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
x.grad == 4 * x

tensor([True, True, True, True])

In [18]:
# y = x.sum() 求导
x.grad.zero_() # 先清空
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

###  2.5.2 非标量反向传播 (防坑指南)

**核心法则**：PyTorch 默认只允许对 **标量 (单一数字)** 调用 `.backward()`！

如果函数的输出 `y` 是一个向量或矩阵：
- **错误做法**：直接 `y.backward()` 会报错。
- **正确做法**：先用 `y.sum()` 或 `y.mean()` 把结果融合成一个单一数字（总 Loss），然后再 `y.sum().backward()`。

*(注：书里的 `y.backward(torch.ones(len(x)))` 是一种底层语法，实战中极少直接用，无脑用 `sum()` 就对了！)*

In [ ]:
x.grad.zero_()
y = x * x # 并非点积
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

### 2.5.3 分离计算 (.detach) 的核心心法

**大白话**：`.detach()` 就是“失忆魔法”或者“剪断求导电线”。

- **作用**：把一个通过复杂运算得到的变量，强行变成一个毫无背景故事的**纯数字（常数）**。
- **后果**：当你反向传播（backward）时，梯度走到这个被 detach 的变量就会停住，不会再继续往前传。
- **应用场景**：迁移学习时用来“冻结”别人训练好的模型，不让我们的破烂数据污染人家辛辛苦苦训练出来的完美参数。

In [ ]:
# 如果你正常对 z 呼叫反向传播 z.backward()，PyTorch 会顺藤摸瓜，用复合导数的链式法则，算出 z 对 x 的导数是 3x^2。
# 但是，如果你突然中二病发作，想跟 PyTorch 说：“在算 z 的时候，请把 y 当作一个毫无感情的数字常数，忘记它是怎么从 x 算出来的！” 这时候，就需要用到 .detach() 这个“失忆魔法”了。
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

### 2.5.4 动态计算图（PyTorch 的灵魂）

**大白话总结：**
- PyTorch 的计算图是 **“边跑边画”** 的（动态图）。
- 就算代码里写满了 `if`、`else`、`while`、`for`，哪怕每次运行循环的次数都不一样，PyTorch 也能精准记录下**当次执行的真实轨迹**。
- **威力**：因为有这个机制，只要你的函数本质上是分段连续的，你就可以肆无忌惮地在深度学习模型里用 Python 的原生控制流，`.backward()` 绝对不会算错方向。

In [22]:
import torch

# 1. 定义一个带有复杂 if 和 while 的函数
def f(a):
    b = a * 2
    # 只要 b 的绝对值（范数）不到 1000，就一直翻倍
    while b.norm() < 1000:
        b = b * 2
    # 分支判断
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

# 2. 随机生成一个标量 a，并开启梯度追踪
a = torch.randn(size=(), requires_grad=True)
print("随机生成的输入 a:", a.item())

# 3. 前向传播：把 a 扔进复杂的函数里算出 d
d = f(a)
print("计算出的结果 d:", d.item())

# 4. 反向传播：自动求导
d.backward()
print("PyTorch 算出的梯度 a.grad:", a.grad.item())
print("数学推导的真实梯度 d / a:", (d / a).item())

# 5. 终极验证：它们相等吗？
print("梯度计算是否完全正确？", a.grad == d / a)

随机生成的输入 a: -0.054836247116327286
计算出的结果 d: -179687.421875
PyTorch 算出的梯度 a.grad: 3276800.0
数学推导的真实梯度 d / a: 3276800.25
梯度计算是否完全正确？ tensor(False)


### 避坑指南：梯度累加的陷阱 (Day 2 易错点)

**核心概念**：
PyTorch 里的梯度默认是 **累加（纯加法）** 的，绝对不会自动覆盖！

**场景还原**：
假设函数 $y = 2x^2$，求导公式为 $4x$。当输入 $x=3$ 时：
- **第一次运行 `y.backward()`**：引擎算出当前梯度是 `12.0`，写进记事本。
- **如果没有清零，紧接着第二次运行 `y.backward()`**：引擎再次算出一个 `12.0`，它会直接**加到原来的记录上**！
- **最终 `x.grad` 的结果**：`12.0 + 12.0 = 24.0`（注意是加法，不是乘法）。

**🛡️ 炼丹黄金法则**：
在每一次计算新的梯度之前，**必须、一定、绝对**要执行 `x.grad.zero_()` 把“黑板”擦干净！否则在未来的循环训练中，梯度会无限膨胀，导致模型直接崩溃。