**1. 向量到底是什么？**
- 不要当成死板的数字表格，要想象成坐标系里有长度和方向的**箭头**。
- 空间里的每一个点，都可以看作是从原点射出的一个箭头。

**2. 基向量与线性组合：空间的“基本粒子”**
- $\hat{i}$ 和 $\hat{j}$ 就是网格的横纵基本单位（比如向右 1 步，向上 1 步）。
- 空间里任何一个向量，不过是把这两个基本单位**拉伸缩短**然后再**相加**组合出来的结果。

**3. 矩阵就是“动词”**
- 矩阵不是一堆数字，而是一种**对空间的变换（拉扯、挤压、旋转）**。
- 当一个矩阵乘一个向量，脑海里的画面应该是：**把这个向量扔进一个正在扭曲的空间里，看看它最后落在哪**。
- 矩阵里的列向量，记录的就是变换后，原来的 $\hat{i}$ 和 $\hat{j}$ 跑到了什么新位置。

**4. 矩阵乘法 = 连续的动作**
- 两个矩阵相乘（比如 $AB$），不是枯燥的算术题，而是**连续做两次空间变换**。
- 顺序是从右往左读：先做 $B$ 变换，再接着做 $A$ 变换（就像穿衣服，先穿内衣 $B$，再穿外套 $A$）。

# Day 2: 李宏毅机器学习核心概念

**核心思想**：机器学习本质上就是 **“让机器自己去寻找一个最合适的函数”**。

### 找函数三步曲 (以预测频道播放量为例)

**Step 1: 定义模型 (Model)**
- 机器不知道函数长什么样，需要我们先“猜”一个大致框架。
- 最简单的线性模型：$y = wx + b$
- $x$ 是已知的特征 (比如昨天的播放量)，$w$ 是权重 (Weight)，$b$ 是偏置 (Bias)，这两个是机器需要找的未知参数。

**Step 2: 定义损失函数 (Loss)**
- 设定一个“烂度”指标，用来评估当前这组 $w$ 和 $b$ 算出来的结果，距离真实数据有多大的偏差。
- Loss 越大，说明模型越烂；目标就是想尽办法让 Loss 越小越好。

**Step 3: 优化参数 (Optimization)**
- **核心武器**：梯度下降 (Gradient Descent)。
- **大白话理解**：就像蒙着眼睛找下山的路。计算一下当前位置脚底下的坡度（求导/算梯度），哪边往下指，就往哪边迈一步（更新参数）。
- 一步步迭代，直到走到谷底（Loss 最小的地方），此时手里的参数就是最佳参数。

---

### 从机器学习到深度学习

- **线性模型的局限 (Model Bias)**：直线就是直线，再怎么调也拟合不出复杂的规律曲线。
- **破局之法**：把许多个简单的非线性函数（比如 Sigmoid 或 ReLU）像拼乐高一样组合起来，就能逼近世界上任何复杂的折线/曲线。
- 当这些函数一层一层叠得非常深、参数量非常庞大时，这个模型就叫做**神经网络 (Neural Network)**，也就是我们说的**深度学习 (Deep Learning)**。

In [8]:
# pytorch 导入的是 torch
import torch

# 用 arange 创建一个行向量 x 包含以0开始的前12个整数
x = torch.arange(12)
print(x)

# 可以通过张量的 shape 属性来访问张量的形状
print(x.shape)

# 元素个数
print(x.numel())

# 改变已有张量的形状
X = x.reshape(3, 4)
print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
import torch

# 设置一些全0的张量
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
import torch

# 设置一些全1的张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])